docs/node-operators/introduction.md, docs/node-operators/resources/faq.md, docs/node-operators/resources/parameters/mainnet.md, docs/node-operators/resources/parameters/testnet.md, docs/node-operators/resources/security.md, docs/node-operators/setup/cli.md, docs/node-operators/setup/generate-keys.md, docs/node-operators/setup/introduction.md, docs/node-operators/setup/latest.md, docs/node-operators/setup/mainnet/archive.md, docs/node-operators/setup/mainnet/bridge.md, docs/node-operators/setup/mainnet/combined.md, docs/node-operators/setup/mainnet/non-validator.md, docs/node-operators/setup/mainnet/validator.md, docs/node-operators/setup/testnet/archive.md, docs/node-operators/setup/testnet/combined.md, docs/node-operators/setup/testnet/non-validator.md
Fixed MD violations as per requirements
* Added blank lines around headers
*  Added blank lines around lists
*  Removed Occasional trailing spaces
Closes:
=> Fix: Markdown violations in Node operators page - Issue #168

utils/vale/styles/Vocab/Ronin/accept.txt
Added ronin-related terms as per requirements
Closes:
Added the terms to the accept.txt file from git utils/vale/styles/Vocab/Ronin/accept.txt.
=> fix:Add Ronin-related terms to Vale vocabulary#169

docs/node-operators/setup/latest.md
set correct saigon release
Closes:
Changed Saigon release to telescope
- [] For content changes, I've completed the [self-review checklist](https://github.com/axieinfinity/ronin-documentation/blob/main/docs/CONTRIBUTING.md#self-review-checklist).
=> Update latest.md, set correct saigon release

docs/basics/tokenomics.md
Closes:
Added a paragraph about ecosystem fund
=> Ecosystem fund in tokenomics

docs/CONTRIBUTING.md
Closes: N/A
Fixes a typo in the contribution guide.
=> fix: typo in the contribution guide

docs/community/join.md, docusaurus.config.js, sidebars.js, src/components/homepage-features/Features.tsx
Closes: N/A
- Reduces the number of clicks to the Community page from two (**Community > Join**) to just one (**Community**). 
- Updates the link to the developer documentation in the footer.
=> refactor: community page

docs/node-operators/setup/latest.md, docs/node-operators/setup/testnet/archive.md, docs/node-operators/setup/testnet/combined.md, docs/node-operators/setup/testnet/non-validator.md
Ranchu version upgrade on saigon
latest.md -> updated testnet version
Saigon setup guides -> added BLS Vars
=> Updated docs for Ranchu

docs/node-operators/setup/cli.md, docs/node-operators/setup/generate-keys.md, docs/node-operators/setup/latest.md, docs/node-operators/setup/mainnet/combined.md, docs/node-operators/setup/mainnet/validator.md
Update docs with latest Lucas upgrade (v2.6.2) and fast finality BLS instructions.
- latest node image version to `ronin:v2.6.2-800ec03`
- bumped minimal go version to `1.20` (required for fast finality)
- completed example `.env` and `docker-compose.yml` files for validators with variables related to fast finality
=> Lucas upgrade (v2.6.2)

docs/node-operators/setup/mainnet/archive.md, docs/node-operators/setup/mainnet/bridge.md, docs/node-operators/setup/mainnet/combined.md, docs/node-operators/setup/mainnet/non-validator.md, docs/node-operators/setup/mainnet/validator.md
- Update guide to download Ronin snapshot when setup node.
=> [Node-operator] update snapshot guide.

src/pages/index.tsx
Closes: #227
Adds a tagline "Welcome to the Ronin chain documentation." instead of "Ronin documentation".
=> chore: add tagline

docs/bridge-operators/setup/overview.md, docs/bridge-operators/setup/run-bridge-operator.md, docs/bridge-operators/slashing.md, docs/validators/setup/overview.md
=> Add bridge operator requirements and slash rule

docs/bridge-operators/setup/run-bridge-operator.md, docs/validators/setup/mainnet/run-archive.md, docs/validators/setup/mainnet/run-combined.md, docs/validators/setup/mainnet/run-non-validator.md, docs/validators/setup/mainnet/run-validator.md
=> feat enhance bridge docs ronin stats integration

docs/apps/rns/trade.md
Closes: N/A
Describes how to trade an RNS domain on Mavis Market in greater detail.
=> fix: description on Trade

docs/apps/rns/guides/register/auctioned.md, docs/apps/rns/manage.md, docs/apps/rns/overview.md, docs/apps/rns/reference/faq.md, docs/apps/rns/trade.mdx
Closes: N/A
* Improves description in the metadata for select RNS pages
* Adds a paragraph about what happens to an auctioned RNS name after the auction ends
=> chore: rewrite meta descriptions

docs/CONTRIBUTING.md, docs/community/contribute/templates.md
Closes: N/A
Removes and changes some headings in the contribution guide.
=> fix: update contribution guide and templates

docs/apps/ronin-bridge.md
Closes: #253 
Withdrawal limits on Ronin Bridge: [https://docs.roninchain.com/apps/ronin-bridge](https://docs.roninchain.com/apps/ronin-bridge)
=> fix: bridge withdrawal limits

docs/apps/katana.md, docs/apps/multisig.md, docs/apps/ron-staking.md, docs/apps/ronin-bridge.md, docs/apps/ronin-explorer.md, docs/get-started.mdx, docs/validators/setup/parameters/mainnet.md, docs/validators/setup/parameters/testnet.md, docs/validators/setup/testnet/run-archive.md, docs/validators/setup/testnet/run-combined.md, docs/validators/setup/testnet/run-non-validator.md, src/pages/index.tsx
Closes: #255 
- Replace `saigon-stats.roninchain.com` with `ronin-stats-ws.roninchain.com` in testnet node setup guides.
- Change copy on the home page [docs.roninchain.com](https://docs.roninchain.com)
=> feat: change stats URL in testnet guides

docs/basics/rewards.md, docs/basics/white-paper.md
Closes: N/A
Adds a description of bridge rewards' allocation to the **Bridge rewards** section of the **Rewards** page.
=> refactor: bridge operator reward

docs/validators/setup/upgrade-validator.md
=> Update Ronin latest version

docusaurus.config.js
Closes: N/A
Adds a link to the Ronin brand kit in the footer.
=> feat: add link to Ronin brand kit

docs/bridge-operators/index.mdx, docs/delegators/index.mdx, docs/get-started.mdx, docs/validators/index.mdx
Closes: N/A
Adds descriptions for index pages:
* [https://docs.roninchain.com/get-started](https://docs.roninchain.com/get-started/)
* [https://docs.roninchain.com/delegators](https://docs.roninchain.com/delegators/)
* [https://docs.roninchain.com/validators](https://docs.roninchain.com/validators/)
* [https://docs.roninchain.com/bridge-operators](https://docs.roninchain.com/bridge-operators/)
=> feat: add description for index pages

docs/apps/ronin-bridge/reference/withdrawal-limits.md
Closes: N/A
Adds withdrawal limit for BANANA token.
=> feat: add BANANA token limits

docs/bridge-operators/setup/upgrade-bridge-operator.md
=> bump version bridge to 0.2.9

docs/apps/katana.md, docs/apps/multisig.md, docs/apps/ron-staking.md, docs/apps/ronin-bridge/guides/deposit-nft.md, docs/apps/ronin-bridge/guides/deposit-token.md, docs/apps/ronin-bridge/guides/withdraw-nft.md, docs/apps/ronin-bridge/guides/withdraw-token.md, docs/apps/ronin-bridge/overview.md, docs/apps/ronin-bridge/reference/withdrawal-limits.md, docs/apps/ronin-explorer.md
Closes: N/A
Adds the YGG token to the Ronin Bridge documentation, specifically the withdrawal limit table and the homepage.
=> feat: add YGG

docs/apps/ronin-bridge/reference/withdrawal-limits.md
Closes: N/A
Adds APRS token to bridge withdrawal limits.
=> feat: add APRS to bridge withdrawal limits

docs/apps/ronin-bridge/guides/deposit-nft.md, docs/apps/ronin-bridge/guides/withdraw-nft.md
Closes: N/A
Reduces wordiness in the token approval steps.
=> feat: simplify token approval step
